"""
Phase 2: Root Cleanup Audit
Identifies unnecessary files and directories for removal
"""

import os
from pathlib import Path
import shutil

def get_dir_size(path):
    """Calculate total size of directory"""
    total = 0
    try:
        for entry in os.scandir(path):
            if entry.is_file(follow_symlinks=False):
                total += entry.stat().st_size
            elif entry.is_dir(follow_symlinks=False):
                total += get_dir_size(entry.path)
    except:
        pass
    return total

def format_size(size_bytes):
    """Format bytes to human readable"""
    for unit in ['B', 'KB', 'MB', 'GB']:
        if size_bytes < 1024.0:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024.0
    return f"{size_bytes:.1f} TB"

def audit_root_cleanup():
    """Audit root directory for unnecessary files"""

    print("Starting Phase 2: Root Cleanup Audit")
    print("=" * 80)
    print()

    # Files to delete
    delete_files = [
        'nul',
        'comprehensive_fix_test.log',
        'content_generation_progress.txt',
        'test_taxonomy.sh'
    ]

    # Directories to optionally delete (backup first)
    optional_delete_dirs = [
        'archived_scripts',
        '.cleanup_backup',
        'test_backup'
    ]

    # Files to keep
    keep_files = [
        'requirements.txt',  # Needed for Python scripts
        'hugo_stats.json',   # Generated by Hugo
        '.hugo_build.lock'   # Hugo lock file
    ]

    print("[!] FILES TO DELETE (Immediate)")
    print("-" * 80)

    total_delete_size = 0
    for filename in delete_files:
        filepath = Path(filename)
        if filepath.exists():
            size = filepath.stat().st_size
            total_delete_size += size
            print(f"[X] {filename:40s} {format_size(size):>10s}")
            print(f"    Reason: Development artifact / test file")
        else:
            print(f"[OK] {filename:40s} (already removed)")

    print(f"\nTotal to delete: {format_size(total_delete_size)}")
    print()

    print("[?] DIRECTORIES TO REVIEW (Optional deletion)")
    print("-" * 80)

    total_optional_size = 0
    for dirname in optional_delete_dirs:
        dirpath = Path(dirname)
        if dirpath.exists() and dirpath.is_dir():
            size = get_dir_size(dirpath)
            total_optional_size += size

            # Count files
            file_count = sum(1 for _ in dirpath.rglob('*') if _.is_file())

            print(f"[?] {dirname:40s} {format_size(size):>10s} ({file_count} files)")

            if dirname == 'archived_scripts':
                print(f"    Reason: Old scripts, no longer used in production")
            elif dirname == '.cleanup_backup':
                print(f"    Reason: Previous cleanup backup, can be removed if stable")
            elif dirname == 'test_backup':
                print(f"    Reason: Test backup, can be removed")
        else:
            print(f"[OK] {dirname:40s} (not found)")

    print(f"\nTotal optional: {format_size(total_optional_size)}")
    print()

    print("[OK] FILES TO KEEP")
    print("-" * 80)
    for filename in keep_files:
        filepath = Path(filename)
        if filepath.exists():
            size = filepath.stat().st_size
            print(f"[+] {filename:40s} {format_size(size):>10s}")
        else:
            print(f"[!] {filename:40s} (missing - may need to regenerate)")
    print()

    # Check for other potentially unnecessary files
    print("[*] OTHER ROOT FILES (Review)")
    print("-" * 80)

    review_patterns = ['*.log', '*.txt', 'temp*', 'tmp*', '*.bak']
    root_path = Path('.')

    found_review = False
    for pattern in review_patterns:
        for filepath in root_path.glob(pattern):
            if filepath.is_file():
                if filepath.name not in delete_files and filepath.name not in keep_files:
                    size = filepath.stat().st_size
                    print(f"[?] {filepath.name:40s} {format_size(size):>10s}")
                    found_review = True

    if not found_review:
        print("[OK] No other files need review")
    print()

    # Summary
    print("=" * 80)
    print("[*] CLEANUP SUMMARY")
    print("=" * 80)
    print(f"Files to delete immediately: {len([f for f in delete_files if Path(f).exists()])}")
    print(f"Space to free (immediate): {format_size(total_delete_size)}")
    print(f"Directories for optional removal: {len([d for d in optional_delete_dirs if Path(d).exists()])}")
    print(f"Space to free (optional): {format_size(total_optional_size)}")
    print(f"Total potential space savings: {format_size(total_delete_size + total_optional_size)}")
    print()

    print("[ACTION] NEXT STEPS")
    print("-" * 80)
    print("[ ] Review files listed above")
    print("[ ] Delete immediate files (nul, logs, test files)")
    print("[ ] Consider removing archived_scripts/ and backup directories")
    print("[ ] Commit cleanup changes")
    print()

    return delete_files, optional_delete_dirs

if __name__ == "__main__":
    audit_root_cleanup()
